#!/usr/bin/env python

import roslib; roslib.load_manifest('ucontroller_tilaunchpad')

import json, sys
import rospy
from std_msgs.msg import String
from geometry_msgs.msg import Twist

def talker():
    pub = rospy.Publisher('lm4f', Twist)
    rospy.init_node('talker', anonymous=True)
    r = rospy.Rate(5) # 5hz
    msg = Twist()
    msg.linear.x = 0.01
    msg.linear.y = 0.06
    msg.angular.z = 0.11
    while not rospy.is_shutdown():
        try:
            msg.linear.x += 0.01; msg.linear.y += 0.01;
            msg.angular.z += 0.01
            rospy.loginfo(msg)
            pub.publish(msg)
            r.sleep()
        except:
            print 'exiting publisher...'
            sys.exit()

if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException: pass
